# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16cW-nYd195o4uh86hNms-YORSJygXrQC
"""

# Restaurant Ordering System
# SIF015 - Computer Science Assignment
# Option A

# This list stores all orders
orders = []

# --- FUNCTION 1: Add an order ---
def add_order():
    order_id = input("Enter Order ID: ")
    customer_name = input("Enter Customer Name: ")
    food_item = input("Enter Food Item: ")
    amount = float(input("Enter Amount (Rs.): "))

    order = {
        "id": order_id,
        "name": customer_name,
        "food": food_item,
        "amount": amount,
        "status": "Pending"
    }

    orders.append(order)
    print("Order added successfully!\n")


# --- FUNCTION 2: View all orders ---
def view_orders():
    if len(orders) == 0:
        print("No orders found.\n")
    else:
        print("\n--- All Orders ---")
        for order in orders:
            print(f"Order ID : {order['id']}")
            print(f"Customer : {order['name']}")
            print(f"Food     : {order['food']}")
            print(f"Amount   : Rs. {order['amount']}")
            print(f"Status   : {order['status']}")
            print("-" * 25)
        print()


# --- FUNCTION 3: Search an order by ID ---
def search_order():
    search_id = input("Enter Order ID to search: ")

    found = False

    for order in orders:
        if order["id"] == search_id:
            print("\n--- Order Found ---")
            print(f"Order ID : {order['id']}")
            print(f"Customer : {order['name']}")
            print(f"Food     : {order['food']}")
            print(f"Amount   : Rs. {order['amount']}")
            print(f"Status   : {order['status']}\n")
            found = True
            break

    if not found:
        print("Order not found.\n")


# --- FUNCTION 4: Update order status ---
def update_order_status():
    search_id = input("Enter Order ID to update: ")
    found = False

    for order in orders:
        if order["id"] == search_id:
            print(f"Current Status: {order['status']}")
            new_status = input("Enter new status (Pending / Completed): ")

            if new_status == "Pending" or new_status == "Completed":
                order["status"] = new_status
                print("Status updated successfully!\n")
            else:
                print("Invalid status. Please enter Pending or Completed.\n")

            found = True
            break

    if not found:
        print("Order not found.\n")


# --- FUNCTION 5: Calculate total sales ---
def calculate_total_sales():
    total = 0

    for order in orders:
        total = total + order["amount"]

    print(f"Total Sales: Rs. {total}\n")


# --- FUNCTION 6: Count completed orders ---
def count_completed_orders():
    count = 0

    for order in orders:
        if order["status"] == "Completed":
            count = count + 1

    print(f"Number of Completed Orders: {count}\n")


# --- MAIN MENU (runs in a loop) ---
def main():
    print("Welcome to the Restaurant Ordering System")

    while True:
        print("========== MENU ==========")
        print("1. Add Order")
        print("2. View Orders")
        print("3. Search Order")
        print("4. Update Order Status")
        print("5. Calculate Total Sales")
        print("6. Count Completed Orders")
        print("7. Exit")
        print("==========================")

        choice = input("Enter your choice (1-7): ")

        if choice == "1":
            add_order()
        elif choice == "2":
            view_orders()
        elif choice == "3":
            search_order()
        elif choice == "4":
            update_order_status()
        elif choice == "5":
            calculate_total_sales()
        elif choice == "6":
            count_completed_orders()
        elif choice == "7":
            print("Thank you! Goodbye.")
            break
        else:
            print("Invalid choice. Please enter a number between 1 and 7.\n")


# Run the program
main()